# Generated by Django 4.1 on 2022-09-02 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Diet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Type of diet", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Ingredients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="ingredient", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of Recipe", max_length=250),
                ),
                (
                    "who_entered",
                    models.CharField(
                        blank=True, help_text="user name", max_length=100, null=True
                    ),
                ),
                (
                    "cook_time",
                    models.CharField(help_text="total cooking time", max_length=50),
                ),
                ("directions", models.TextField()),
                (
                    "difficulty_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Easy", "Easy"),
                            ("Medium", "Medium"),
                            ("Difficult", "Difficult"),
                            ("Extremely Difficult", "Extremely Difficult"),
                        ],
                        help_text="What level of skill does this recipe require?",
                        max_length=20,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        help_text="is there a source you'd like to cite for this recipe? Enter a book name or link here",
                        max_length=250,
                    ),
                ),
                (
                    "diet",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="recipe.diet",
                    ),
                ),
                (
                    "ingredients",
                    models.ManyToManyField(
                        help_text="add ingredient", to="recipe.ingredients"
                    ),
                ),
            ],
        ),
    ]
