# Generated by Django 4.1 on 2022-10-05 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Diet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Type of diet", max_length=200)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of Recipe", max_length=250),
                ),
                (
                    "who_entered",
                    models.CharField(
                        blank=True, help_text="user name", max_length=100, null=True
                    ),
                ),
                (
                    "cook_time",
                    models.CharField(help_text="total cooking time", max_length=50),
                ),
                ("directions", models.TextField()),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("Easy", "Easy"),
                            ("Medium", "Medium"),
                            ("Difficult", "Difficult"),
                            ("Extremely Difficult", "Extremely Difficult"),
                        ],
                        help_text="What level of skill does this recipe require?",
                        max_length=20,
                    ),
                ),
                ("ingredients", models.TextField()),
                (
                    "origin",
                    models.CharField(
                        help_text="is there a source you'd like to cite for this recipe? Enter a book name or link here",
                        max_length=250,
                    ),
                ),
                (
                    "associated_recipe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="recipe.recipe",
                    ),
                ),
                (
                    "chef",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("diet", models.ManyToManyField(blank=True, to="recipe.diet")),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
