# Generated by Django 4.1 on 2022-09-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={"ordering": ["title"]},
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="diet",
        ),
        migrations.AddField(
            model_name="recipe",
            name="diet",
            field=models.ManyToManyField(blank=True, null=True, to="recipe.diet"),
        ),
    ]
