# Generated by Django 4.1 on 2022-09-04 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0002_remove_recipe_associated_recipe_associaterecipe_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="associaterecipe",
        ),
        migrations.AddField(
            model_name="recipe",
            name="associated_recipe",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="recipe.recipe",
            ),
        ),
        migrations.DeleteModel(
            name="AssociateRecipe",
        ),
    ]
