# Generated by Django 4.1 on 2022-09-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0002_alter_recipe_options_remove_recipe_diet_recipe_diet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="diet",
            field=models.ManyToManyField(blank=True, to="recipe.diet"),
        ),
    ]
