# Generated by Django 4.1 on 2022-09-06 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipe", "0003_remove_recipe_associaterecipe_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="chef",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="associated_recipe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="recipe.recipe",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="difficulty_level",
            field=models.CharField(
                choices=[
                    ("Easy", "Easy"),
                    ("Medium", "Medium"),
                    ("Difficult", "Difficult"),
                    ("Extremely Difficult", "Extremely Difficult"),
                ],
                help_text="What level of skill does this recipe require?",
                max_length=20,
            ),
        ),
    ]
